Fix #402
microsoft/DefinitelyTyped-tools pull request #404
Opened 2022-02-16 23:32 UTC by plumdog

I think this does fix this particular bug, but - assuming I have built everything correctly in my local env - I now get linting errors that I don't on 0.0.103:

Eg, `npm test through` now gives me a bunch of TypeError chatter, then:
```
ERROR: 3:5  prefer-const  Identifier 'i' is never reassigned; use 'const' instead of 'var'.
```

I don't know if this is expected.

2022-02-16 23:35 UTC, plumdog commented
@AviVahl @andrewbranch Good chance I'm missing something, but this is my attempt. Does now run for me locally.

2022-02-17 00:00 UTC, andrewbranch requested changes
This is going to be dependent upon whether the package being tested is in a versioned subfolder. We should probably just look up until we see the `types` directory and then go one more.

2022-02-17 00:32 UTC, andrewbranch commented
I think you and @sandersn were working on this at the same time: #405

2022-02-17 07:33 UTC, plumdog commented
Closing in favour of #405

2022-02-17 07:33 UTC, closed without merging