Report results from running on-demand DT to github
microsoft/DefinitelyTyped-tools pull request #614
Opened 2023-02-24 20:46 UTC by gabritto

2023-02-27 17:36 UTC, sandersn requested changes
Some minor questions and comments. Looks good overall.

2023-02-27 17:36 UTC, sandersn commented on packages/dtslint-runner/src/post-results.ts
> +      if (branchError.message !== error.message) {
How much noise does this suppress? I assume that it's better than `diff` that we're currently using.

2023-02-27 17:36 UTC, sandersn commented on packages/dtslint-runner/src/post-results.ts
> +  const branchOnlyMessage =
these are likely to be the actually valuable errors. Maybe this should be first, and not inside a `details` tag if there are only 1 - 3 errors?

2023-02-28 17:58 UTC, gabritto commented on packages/dtslint-runner/src/post-results.ts
> +// Args: [auth token] [buildId] [status comment] [user to tag] [issue] [job status] [?nightly errors file] [?branch errors file]
Yes

2023-02-28 18:03 UTC, gabritto commented on packages/dtslint-runner/src/post-results.ts
> +        const nightlyFiles = glob.sync(`**/*.json`, { cwd: nightlyErrorsPath, absolute: true });
1. They're named `nightlyFailuresN.json`, where `N` is the shard number.
2. The nightly and branch runs will be stored in different folders.

2023-02-28 23:55 UTC, sandersn commented
Update from collecting performance statistics from DT: two runs of the same commit showed a significant overall 2.3% speedup on. Another two runs showed a significant 20% speedup in ResolveTypeReference, which is a very short phase of compilation. I don't think the results are going to be reliable enough to use.

2023-03-01 00:17 UTC, gabritto commented
Some test (dtslint/dt-header) is failing, I have no idea why, but I'll investigate once I can get a successful pipeline run.

2023-03-02 22:30 UTC, gabritto commented on packages/dtslint/test/dt-header.test.ts
> +          column: 1,
This PR updates the version of `parsimmon`, a dependency of `header-parser`, from 1.13 to 1.18. Version 1.17 of `parsimmon` changed reporting of error line/column, and so this test needs to be updated to reflect that.

2023-03-02 22:31 UTC, gabritto commented on packages/dtslint/test/dt-header.test.ts
> +    {
As per the above comment, I was wondering if `parsimmon` changed how they parse whitespace (maybe they were now ignoring it?), but it seems they didn't, and this test makes sure of that. So it seems the only change is in the position of the reported error.

2023-03-02 22:43 UTC, sandersn approved these changes
Remember to revert the `slice(0,4)` code used for testing.

2023-03-02 22:43 UTC, sandersn commented on packages/dtslint-runner/src/main.ts
> +  testedPackages = testedPackages.slice(0, 4); // TODO: remove this line after testing, and make `testedPackages` a const.
remember to remove this line

2023-03-02 22:58 UTC, merged